apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  labels:
    app: elasticsearch-service
spec:
  type: ClusterIP
  selector:
    app: elasticsearch-deployment
  ports:
    - port: 9200
      targetPort: 9200