apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # postgres
  POSTGRES_PASSWORD: cG9zdGdyZXM= # postgres
  POSTGRES_DB: cG9zdGdyZXM= # postgres
  AUTHENTICATION_DB_NAME: YXV0aGVudGljYXRpb24= # authentication