apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-deployment
  labels:
    app: kafka-deployment
spec:
  replicas: 2
  serviceName: kafka-service
  selector:
    matchLabels:
      app: kafka-deployment
  template:
    metadata:
      labels:
        app: kafka-deployment
    spec:
      containers:
        - name: kafka-deployment
          image: bitnami/kafka:3.7
          envFrom:
            - configMapRef:
                name: kafka-env
          # compute node id from the pod hostname (ordinal) and start Kafka
          command:
            - sh
            - -c
            - |
              ORD=${HOSTNAME##*-}
              NODE_ID=$((ORD + 1))
              export KAFKA_CFG_NODE_ID="$NODE_ID"

              export KAFKA_CFG_ADVERTISED_LISTENERS="BROKER://${HOSTNAME}.kafka-service.vchat.svc.cluster.local:9092,EXTERNAL://127.0.0.1:9094"

              echo "Starting Kafka with NODE_ID=${KAFKA_CFG_NODE_ID}, advertised=${KAFKA_CFG_ADVERTISED_LISTENERS}"
              exec /opt/bitnami/scripts/kafka/entrypoint.sh /opt/bitnami/scripts/kafka/run.sh
          ports:
            - name: broker
              containerPort: 9092
            - name: controller
              containerPort: 9093
            - name: external
              containerPort: 9094
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami/kafka
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      volumes:
        - name: kafka-data
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui-deployment
  labels:
    app: kafka-ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui-deployment
  template:
    metadata:
      labels:
        app: kafka-ui-deployment
    spec:
      containers:
        - name: kafka-ui-deployment
          image: provectuslabs/kafka-ui:v0.7.2
          envFrom:
            - configMapRef:
                name: kafka-ui-config
          env:
            - name: DYNAMIC_CONFIG_ENABLED
              value: "true"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
