apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-setup
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: cassandra-setup
          image: temporalio/admin-tools:1.26
          command: ["/bin/sh", "-c"]
          args:
            - |
              SCHEMA_DIR=/etc/temporal/schema/cassandra/temporal/versioned
              temporal-cassandra-tool --ep $CASSANDRA_SEEDS:9042 --user "$CASSANDRA_USER" --password "$CASSANDRA_PASSWORD" create -k $KEYSPACE --rf $CASSANDRA_REPLICATION_FACTOR
              temporal-cassandra-tool --ep $CASSANDRA_SEEDS:9042 --user "$CASSANDRA_USER" --password "$CASSANDRA_PASSWORD" -k $KEYSPACE setup-schema -v 0.0
              temporal-cassandra-tool --ep $CASSANDRA_SEEDS:9042 --user "$CASSANDRA_USER" --password "$CASSANDRA_PASSWORD" -k $KEYSPACE update-schema -d $SCHEMA_DIR
          env:
            - name: CASSANDRA_USER
              valueFrom:
                secretKeyRef:
                  name: cassandra-secret
                  key: CASSANDRA_USER
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cassandra-secret
                  key: CASSANDRA_PASSWORD
            - name: CASSANDRA_SEEDS
              value: cassandra-service
            - name: KEYSPACE
              value: temporal
            - name: CASSANDRA_REPLICATION_FACTOR
              value: "1"
