"""empty message

Revision ID: 04132ab81501
Revises: bbd7e8a7730c
Create Date: 2025-07-26 19:57:04.129416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04132ab81501'
down_revision: Union[str, None] = 'bbd7e8a7730c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE devices ALTER COLUMN access_token TYPE UUID USING access_token::UUID")
    op.execute("ALTER TABLE devices ALTER COLUMN refresh_token TYPE UUID USING refresh_token::UUID")
    op.drop_constraint('devices_account_id_fkey', 'devices', type_='foreignkey')
    op.create_foreign_key(None, 'devices', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key('devices_account_id_fkey', 'devices', 'accounts', ['account_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('devices', 'refresh_token',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('devices', 'access_token',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    # ### end Alembic commands ###
