"""empty message

Revision ID: db45d3d28c91
Revises: cfce68127e75
Create Date: 2025-04-01 13:45:30.241761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'db45d3d28c91'
down_revision: Union[str, None] = 'cfce68127e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'access_token',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.alter_column('devices', 'refresh_token',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.create_unique_constraint(None, 'devices', ['account_id', 'client_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='unique')
    op.alter_column('devices', 'refresh_token',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.alter_column('devices', 'access_token',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###
