apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-server-config
data:
  development-cass.yaml: |
    system.forceSearchAttributesCacheRefreshOnRead:
      - value: true # Dev setup only. Please don't turn this on in production.
        constraints: {}
  development-sql.yaml: |
    limit.maxIDLength:
      - value: 255
        constraints: {}
    system.forceSearchAttributesCacheRefreshOnRead:
      - value: true # Dev setup only. Please don't turn this on in production.
        constraints: {}
  docker.yaml: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-server-env
data:
  TEMPORAL_NAMESPACE: vchat
  DB: cassandra
  DB_PORT: "9042"
  CASSANDRA_SEEDS: cassandra-service # cassandra service name
  DYNAMIC_CONFIG_FILE_PATH: /etc/temporal/config/dynamicconfig/development-cass.yaml
  ENABLE_ES: "true"
  ES_SEEDS: elasticsearch-service # elasticsearch service name
  ES_VERSION: v7