apiVersion: v1
kind: Service
metadata:
  name: temporal-server-service
  labels:
    app: temporal-server-service
spec:
  type: ClusterIP
  selector:
    app: temporal-server-deployment
  ports:
    - port: 7233
      targetPort: 7233
